services:
  db:
    image: postgres:16-alpine
    container_name: postgres-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: